// Code generated by protoc-gen-gogo.
// source: internal/internal.proto
// DO NOT EDIT!

/*
Package influxql is a generated protocol buffer package.

It is generated from these files:
	internal/internal.proto

It has these top-level messages:
	Measurements
	Measurement
*/
package influxql

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Measurements struct {
	Items            []*Measurement `protobuf:"bytes,1,rep,name=Items" json:"Items,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Measurements) Reset()                    { *m = Measurements{} }
func (m *Measurements) String() string            { return proto.CompactTextString(m) }
func (*Measurements) ProtoMessage()               {}
func (*Measurements) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{0} }

func (m *Measurements) GetItems() []*Measurement {
	if m != nil {
		return m.Items
	}
	return nil
}

type Measurement struct {
	Database         *string `protobuf:"bytes,1,opt,name=Database" json:"Database,omitempty"`
	RetentionPolicy  *string `protobuf:"bytes,2,opt,name=RetentionPolicy" json:"RetentionPolicy,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Regex            *string `protobuf:"bytes,4,opt,name=Regex" json:"Regex,omitempty"`
	IsTarget         *bool   `protobuf:"varint,5,opt,name=IsTarget" json:"IsTarget,omitempty"`
	SystemIterator   *string `protobuf:"bytes,6,opt,name=SystemIterator" json:"SystemIterator,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Measurement) Reset()                    { *m = Measurement{} }
func (m *Measurement) String() string            { return proto.CompactTextString(m) }
func (*Measurement) ProtoMessage()               {}
func (*Measurement) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{1} }

func (m *Measurement) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *Measurement) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

func (m *Measurement) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Measurement) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *Measurement) GetIsTarget() bool {
	if m != nil && m.IsTarget != nil {
		return *m.IsTarget
	}
	return false
}

func (m *Measurement) GetSystemIterator() string {
	if m != nil && m.SystemIterator != nil {
		return *m.SystemIterator
	}
	return ""
}

func init() {
	proto.RegisterType((*Measurements)(nil), "influxql.Measurements")
	proto.RegisterType((*Measurement)(nil), "influxql.Measurement")
}

func init() { proto.RegisterFile("internal/internal.proto", fileDescriptorInternal) }

var fileDescriptorInternal = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8d, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x87, 0x89, 0xed, 0xca, 0x3a, 0x15, 0x85, 0x41, 0x31, 0x78, 0x5a, 0x7a, 0x90, 0x80, 0xb0,
	0x82, 0x57, 0xaf, 0x5e, 0xf6, 0xa0, 0x48, 0xf4, 0x05, 0x46, 0x19, 0x4b, 0x20, 0x7f, 0x34, 0x99,
	0x42, 0xfb, 0x78, 0xbe, 0x99, 0x34, 0xa5, 0x65, 0xd9, 0xdb, 0xef, 0xfb, 0xf2, 0x85, 0x81, 0x1b,
	0x17, 0x85, 0x73, 0x24, 0xff, 0x70, 0x18, 0xfd, 0x4f, 0x4e, 0x92, 0xb0, 0x75, 0xf1, 0xdb, 0xaf,
	0x37, 0xbf, 0x7e, 0xf9, 0x04, 0xe7, 0x2f, 0x4c, 0x65, 0x9d, 0x39, 0x70, 0x94, 0x82, 0xf7, 0xd0,
	0x0c, 0xc2, 0xa1, 0x68, 0xd5, 0xcd, 0xcc, 0xe2, 0xf1, 0xba, 0x3f, 0x94, 0xfd, 0x28, 0xb3, 0xfb,
	0x66, 0xf9, 0xa7, 0x60, 0x31, 0xd2, 0x78, 0x0b, 0xed, 0x33, 0x09, 0x7d, 0x52, 0x61, 0xad, 0x3a,
	0x65, 0xce, 0xec, 0x91, 0xd1, 0xc0, 0xa5, 0x65, 0xe1, 0x28, 0x2e, 0xc5, 0xb7, 0xe4, 0xdd, 0xd7,
	0x56, 0x9f, 0xd4, 0x64, 0xaa, 0x11, 0x61, 0xfe, 0x4a, 0x81, 0xf5, 0xac, 0x3e, 0xd7, 0x8d, 0x57,
	0xd0, 0x58, 0x5e, 0xf1, 0x46, 0xcf, 0xab, 0xdc, 0xc3, 0xee, 0xde, 0x50, 0x3e, 0x28, 0xaf, 0x58,
	0x74, 0xd3, 0x29, 0xd3, 0xda, 0x23, 0xe3, 0x1d, 0x5c, 0xbc, 0x6f, 0x8b, 0x70, 0x18, 0x84, 0x33,
	0x49, 0xca, 0xfa, 0xb4, 0x7e, 0x9d, 0xd8, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xca, 0xf0, 0x3f,
	0x34, 0x24, 0x01, 0x00, 0x00,
}
